# Schema for the configuration files of the page hits module.

page_hits.settings:
  type: config_object
  label: 'Page Hits settings'
  mapping:
    increment_page_count_for_admin:
      type: integer
      label: 'Increment page count for admin user'
    show_user_ip_address:
      type: integer
      label: 'Show IP address of user'
    show_unique_page_visits:
      type: integer
      label: 'Show total number of unique page visits'
    show_total_page_count:
      type: integer
      label: 'Show total number of page visits'
    show_page_count_of_logged_in_user:
      type: integer
      label: 'Show total number of page visits by logged in user'
    show_total_page_count_of_week:
      type: integer
      label: 'Show total number of page visits of the week'
